<!DOCTYPE html>
<html lang="en">
<head>
    <title>${title}</title>
</head>
<body>
    <textarea id = "code_snippet"> // write your code here </textarea><br><br>
    <label for="time_restriction">Time restriction:</label>
    <input id="time_restriction" type="text" value="0"/><br><br>
    <label for="views_restriction">Views restriction</label>
    <input id="views_restriction" type="text" value="0"/><br><br>
    <button id = "send_snippet" type= "submit" onclick="send()">Submit</button>
</body>
</html>
